import type { ApplicationRecord, CandidateProfile, JobPosting } from './types.js';

export const demoCandidate: CandidateProfile = {
  id: 'candidate-kaushal',
  headline: 'Senior software engineer focused on AI-enabled full-stack products',
  skills: [
    { name: 'TypeScript', years: 5, aliases: ['JavaScript', 'JS'] },
    { name: 'React', years: 5 },
    { name: 'Node.js', years: 5, aliases: ['Node'] },
    { name: 'Python', years: 4 },
    { name: 'PostgreSQL', years: 4, aliases: ['SQL'] },
    { name: 'AWS', years: 3 },
    { name: 'LLM Applications', years: 2, aliases: ['AI', 'OpenAI'] },
  ],
  industries: ['SaaS', 'Developer Tools', 'FinTech'],
  domains: ['AI Products', 'Developer Tools', 'Workflow Automation'],
  yearsOfExperience: 6,
  seniority: 'senior',
  locations: ['New York, NY', 'Remote'],
  workAuthorization: ['United States'],
  salaryExpectation: { currency: 'USD', minimum: 150000 },
};

export const demoJobs: JobPosting[] = [
  {
    id: 'job-001',
    title: 'Senior Full-Stack Engineer, AI Workflows',
    company: {
      id: 'company-orbit',
      name: 'OrbitWorks',
      size: '201-500',
      fundingStage: 'Series B',
      headquarters: 'New York, NY',
      techStack: ['TypeScript', 'React', 'Node.js', 'PostgreSQL', 'OpenAI'],
      hiringTrends: 'Expanding the AI workflow engineering team after a Series B raise.',
      recentEngineeringNews: ['Launched a workflow builder for customer support teams.'],
      interviewDifficulty: 'medium',
      estimatedResponseRate: 0.32,
    },
    department: 'Engineering',
    locations: ['New York, NY', 'Remote'],
    workMode: 'hybrid',
    employmentType: 'full-time',
    minimumYears: 5,
    seniority: 'senior',
    salary: { currency: 'USD', minimum: 165000, maximum: 210000 },
    source: 'Seeded demo provider',
    directApplyUrl: 'https://example.com/orbitworks/jobs/001',
    originalPostedAt: '2026-06-05',
    lastUpdatedAt: '2026-06-24',
    requiredSkills: ['TypeScript', 'React', 'Node.js'],
    preferredSkills: ['PostgreSQL', 'LLM Applications', 'AWS'],
    industries: ['SaaS', 'Developer Tools'],
    description: 'Build AI-assisted workflow tools, integrations, and dashboard experiences for technical operations teams.',
  },
  {
    id: 'job-002',
    title: 'Backend Platform Engineer',
    company: {
      id: 'company-ledger',
      name: 'LedgerLane',
      size: '501-1000',
      fundingStage: 'Series C',
      headquarters: 'San Francisco, CA',
      techStack: ['Python', 'Go', 'Kubernetes', 'AWS'],
      hiringTrends: 'Hiring infrastructure engineers to improve payment reliability.',
      interviewDifficulty: 'high',
      estimatedResponseRate: 0.21,
    },
    department: 'Platform',
    locations: ['San Francisco, CA'],
    workMode: 'onsite',
    employmentType: 'full-time',
    minimumYears: 7,
    seniority: 'staff',
    salary: { currency: 'USD', minimum: 180000, maximum: 240000 },
    source: 'Seeded demo provider',
    directApplyUrl: 'https://example.com/ledgerlane/jobs/002',
    originalPostedAt: '2026-06-14',
    lastUpdatedAt: '2026-06-22',
    requiredSkills: ['Python', 'Kubernetes', 'AWS'],
    preferredSkills: ['Go', 'Payments'],
    industries: ['FinTech'],
    description: 'Own backend services, platform reliability, and deployment tooling for high-volume payments infrastructure.',
  },
  {
    id: 'job-003',
    title: 'Frontend Product Engineer',
    company: {
      id: 'company-mentor',
      name: 'MentorMesh',
      size: '51-200',
      fundingStage: 'Seed',
      headquarters: 'Remote',
      techStack: ['React', 'TypeScript', 'GraphQL'],
      hiringTrends: 'Small team looking for product-minded engineers.',
      interviewDifficulty: 'low',
      estimatedResponseRate: 0.45,
    },
    department: 'Product Engineering',
    locations: ['Remote'],
    workMode: 'remote',
    employmentType: 'full-time',
    minimumYears: 3,
    seniority: 'mid-senior',
    salary: { currency: 'USD', minimum: 130000, maximum: 170000 },
    source: 'Seeded demo provider',
    directApplyUrl: 'https://example.com/mentormesh/jobs/003',
    originalPostedAt: '2026-06-10',
    lastUpdatedAt: '2026-06-25',
    requiredSkills: ['React', 'TypeScript'],
    preferredSkills: ['GraphQL', 'Design Systems'],
    industries: ['EdTech'],
    description: 'Create polished mentoring marketplace experiences with a focus on conversion, accessibility, and UX quality.',
  },
];

export const demoApplications: ApplicationRecord[] = demoJobs.map((job, index) => ({
  id: `application-${job.id}`,
  jobId: job.id,
  state: index === 0 ? 'interested' : 'saved',
  updatedAt: new Date('2026-06-26T00:00:00.000Z').toISOString(),
}));
